# Generated by Django 4.1.3 on 2022-11-15 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nickname",
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "남자"), (1, "여자")],
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(2)],
            ),
        ),
    ]
