# Generated by Django 4.1.3 on 2022-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to="user_path/%Y/%m/%d"),
        ),
    ]
