# Generated by Django 4.1.3 on 2022-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="column",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
