# Generated by Django 4.1.3 on 2022-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_column_image_alter_column_title_alter_event_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
